#!/bin/sh

which aws 
aws=$?

set -e
host=$(hostname)
if [ "$1" = "local" ]
then
    echo "Local build of the NPM package, then install it in node_modules"
    set -x
    ./node_modules/.bin/ng build spotfire-wrapper 
    (cd projects/spotfire-wrapper/ ; npm run build )
    (cd build/spotfire-wrapper/ ; npm pack) 
    mkdir -p dist
    cp -f build/spotfire-wrapper/*.tgz dist/spotfire-wrapper.tgz 
    npm install /opt/tibco/users/spotfire-wrapper/dist/spotfire-wrapper.tgz --no-save
    set +x
    date
    npm run build:elements --prod
    
    echo "That's all folks!"
    exit 0
fi
if [ $aws -eq 1 ]
then
    echo "CAUTION: aws is not installed on $host."
    echo "         SpotfireWrapper JS library won't be published at https://github.com/TIBCOSoftware/spotfire-wrapper/dist/"
    echo "         but in ./build"
    export WORKSPACE=$(pwd)
    mkdir -p ${WORKSPACE}/dist
else
    export AWS_DEFAULT_PROFILE=sb
    date
    pwd
    env | sort
fi

repl() { printf -- "$1"'%.s' $(eval "echo {1.."$(($2))"}"); }
title() {
    title=$1
    echo ""
    echo "=========================================================================================="
    echo $title
    repl "- " $((${#title}/2+1))
    echo ""
}
rm -rf node_modules/\@tibco node_modules/spotfire-w*

title "Install dependencies:"
npm install


title "[spotfire-wrapper] Build the NPM package:"
./node_modules/.bin/ng build spotfire-wrapper
(cd projects/spotfire-wrapper/ ; npm run build )

# if [ "$HOSTNAME" = "vmkabirabld1.tibco.com" ]
if [ "$HOSTNAME" = "rcxxxxbld12" ]
then
    title "[spotfire-wrapper] Publish the NPM package to artifacts.tibco.com:"

    # trick to be logged as jenkins to verdaccio (to publich spotfire-wrapper NPM package)
    echo "## DO NOT MODIFY !! (Nicolas Deroche - March 2019) ##" > ~/.npmrc
    echo "## This script is generated by script build.sh (cf Jenkins job UI_SpotfireWrapper_Develop)"  >> ~/.npmrc
    curl -ureward-deployment:AP8V7oMPFGgtE2eZFMPC2mEHMjfNN7PyUvRa3h "http://artifacts.tibco.com:8081/artifactory/api/npm/npm-general/auth/tibco" >> ~/.npmrc
    (cd build/spotfire-wrapper ; npm publish  --access public)
else
    title "[spotfire-wrapper] Create the NPM package:"
    (cd build/spotfire-wrapper/ ; npm pack)
    title "[spotfire-wrapper] Copy the NPM package to local build directory:"
    cp -f ${WORKSPACE}/build/spotfire-wrapper/*.tgz ${WORKSPACE}/dist/spotfire-wrapper.tgz
fi

title "[spotfire-wrapper-lib] Install the NPM package from NPM registry"
echo "The NPM package is used to build the WebElement Library"
npm install @tibco/spotfire-wrapper  --no-save || {
    echo "WARNING: no access to artifacts.tibco.com NPM registry - Trying to install it from ${WORKSPACE}/build/spotfire-wrapper.tgz"
    npm install ${WORKSPACE}/build/spotfire-wrapper.tgz --no-save
}

title "[spotfire-wrapper-lib] Build the WebElement Library:"
npm run build:elements

if [ $aws -eq 0 ]
then
    title "[spotfire-wrapper-lib] Copy the WebElement Library to S3:"
    aws s3 cp elements/spotfire-wrapper.js s3://sf-library/
else
    cp -f elements/spotfire-wrapper.js ${WORKSPACE}/build/
fi

echo ""
echo ""
echo "How to use: "
echo "  - npm config set @tibco:registry http://artifacts.tibco.com:8081/artifactory/api/npm/npm-general"
echo "    npm install @tibco/spotfire-wrapper@latest --save"
echo "  OR"
echo "  - npm install @tibco/spotfire-wrapper@latest --save @tibco:registry "
echo ""
echo "  - <script src='https://github.com/TIBCOSoftware/spotfire-wrapper/dist/spotfire-wrapper.js'></script>"
echo ""
echo ""
[ $aws -eq 1 ] && ls -lrt ${WORKSPACE}/build/
echo ""
echo "Done!"

